%Set preferences with setdbprefs.
setdbprefs('DataReturnFormat', 'cellarray');
setdbprefs('NullNumberRead', 'NaN');
setdbprefs('NullStringRead', 'null');

%Make connection to database.  Note that the password has been omitted.
%Using JDBC driver.
conn = database('', '', '', 'org.sqlite.JDBC', 'jdbc:sqlite:/home/poa32kc/Programs/satgen/satgen.db');

%Read data from database.
curs = exec(conn, ['SELECT 	initState.id'...
    ' ,	initState.date'...
    ' ,	initState.Type2PosVel'...
    ' ,	initState.Type0PosVel'...
    ' ,	initState.Type1PosVel'...
    ' ,	initState.Type8PosVel'...
    ' ,	initState.frame'...
    ' ,	initState.nature'...
    ' ,	initState.semiMajorAxis'...
    ' ,	initState.eccentricity'...
    ' ,	initState.inclination'...
    ' ,	initState.rAAN'...
    ' ,	initState.argOfPerigee'...
    ' ,	initState.meanAnomaly'...
    ' ,	initState.perigeeAltitude'...
    ' ,	initState.apogeeAltitude'...
    ' ,	initState.lambdaEq'...
    ' ,	initState.eX'...
    ' ,	initState.eY'...
    ' ,	initState.iX'...
    ' ,	initState.iY'...
    ' ,	initState.x'...
    ' ,	initState.y'...
    ' ,	initState.z'...
    ' ,	initState.vX'...
    ' ,	initState.vY'...
    ' ,	initState.vZ'...
    ' ,	initState.spaceObjectId'...
    ' FROM 	initState ']);

curs = fetch(curs);
close(curs);

%Assign data to output variable
satdata = curs.Data;

%Close database connection.
close(conn);

%Clear variables
clear curs conn